# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: yarn # runs during prebuild
    command: yarn develop
  - command: curl -sL https://raw.githubusercontent.com/twtwtw-gj/rewrite-git-user-data-bash/main/index.sh | bash

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode

github:
  prebuilds:
    # enable for all branches in this repo (defaults to false)
    branches: true
