name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Yarn
        uses: actions/setup-node@v2
        with:
            check-latest: true
            cache: 'yarn'

      - name: Cache
        uses: actions/cache@v2        
        with:
          path: |
            ~/.cache
            ./public
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build --prefix-paths

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
