name: unit test

on:
  push:
    branches:
      - feature/**
      - fix/**

jobs:
  unit_test:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Yarn
        uses: actions/setup-node@v4
        with:
            node-version: 'node'
            cache: 'yarn'

      - name: Cache
        uses: actions/cache@v4        
        with:
          key: "build"
          path: |
            ~/.cache
            ./public

      - name: Yarn Upgrade
        run: npm upgrade -g yarn@latest

      - name: Install
        run: yarn install

      - name: Test
        run: yarn test
