name: github pages

on:
  push:
    branches:
      - feature/**
      - fix/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Yarn
        uses: actions/setup-node@v2
        with:
            check-latest: true
            cache: 'yarn'

      - name: Cache
        uses: actions/cache@v2        
        with:
          key: "build"
          path: |
            ~/.cache
            ./public

      - name: Install
        run: yarn install

      - name: Test
        run: yarn test
